import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { invoiceService } from "../services/invoiceService";
import { useAuthStore } from "../store/authStore";
import { formatCurrency, formatDate, invoiceStatuses } from "../lib/utils";
import { Button, Card, CardHeader, DataTable, EmptyState, Page, Select, StatusBadge } from "../components/ui/primitives";

export default function InvoicesPage() {
  const { user } = useAuthStore();
  const queryClient = useQueryClient();
  const [status, setStatus] = useState("");
  const invoicesQuery = useQuery({
    queryKey: ["invoices", user?.role, status],
    queryFn: () => user?.role === "ADMIN" ? invoiceService.listAll({ status: status || undefined }) : invoiceService.listMine({ status: status || undefined }),
  });

  const markPaid = useMutation({
    mutationFn: invoiceService.markPaid,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["invoices"] }),
  });

  const columns = useMemo(
    () => [
      { key: "invoiceNo", label: "Invoice" },
      { key: "status", label: "Status", render: (row) => <StatusBadge status={row.status} /> },
      { key: "booking", label: "Booking", render: (row) => row.booking?.id?.slice(0, 8) || "—" },
      { key: "user", label: "Billed To", render: (row) => row.user?.company || row.booking?.shipment?.warehouseId || "—" },
      { key: "pricing", label: "Total", render: (row) => formatCurrency(row.pricing?.total) },
      { key: "issuedAt", label: "Issued", render: (row) => formatDate(row.issuedAt) },
      {
        key: "actions",
        label: "",
        render: (row) => user?.role === "ADMIN" && row.status !== "PAID" ? <Button variant="secondary" onClick={() => markPaid.mutate(row.id)}>Mark paid</Button> : null,
      },
    ],
    [markPaid, user?.role],
  );

  return (
    <Page
      title="Invoices"
      subtitle="Invoice records are generated by the booking service on delivery."
      actions={
        <Select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 min-w-44">
          <option value="">All statuses</option>
          {invoiceStatuses.map((item) => <option key={item}>{item}</option>)}
        </Select>
      }
    >
      <Card>
        <CardHeader title="Invoice ledger" subtitle="Warehouse users see their own invoices. Admin sees the full set." />
        <DataTable
          columns={columns}
          rows={invoicesQuery.data?.items || []}
          empty={<EmptyState title="No invoices found" message="Delivered bookings will generate invoice records here." />}
        />
      </Card>
    </Page>
  );
}
